services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    env_file:
      - BACKEND/.env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysql
    volumes:
      - ./BACKEND:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    container_name: frontend_container
    restart: always
    env_file:
      - FRONTEND/.env
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
    ports:
      - "5173:5173"
    depends_on:
      - mysql
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]

  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"

volumes:
  mysql_data:
