services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    env_file:
      - .env            
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysql
    volumes:
      - ./BACKEND:/app
    working_dir: /app
    command: ["npm", "start"]

  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Thiết lập mật khẩu cho root
      MYSQL_DATABASE: ${DB_NAME}           # Tạo database nếu chưa có
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Đăng nhập bằng root
    ports:
      - "8080:80"

volumes:
  mysql_data:
