services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    env_file:
      - ./BACKEND/.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - greenflag_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    env_file:
      - ./BACKEND/.env
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - greenflag_network

  redis:
    image: redis:7
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - greenflag_network

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    env_file:
      - ./BACKEND/.env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./BACKEND:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]
    networks:
      - greenflag_network

  worker:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: worker_container
    restart: always
    env_file:
      - ./BACKEND/.env
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      - mysql
    volumes:
      - ./BACKEND:/app
      - /app/node_modules
    working_dir: /app
    command: ["node", "src/services/worker.js"]
    networks:
      - greenflag_network

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    container_name: frontend_container
    restart: always
    env_file:
      - ./FRONTEND/.env
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
    ports:
      - "5173:5173"
    depends_on:
      - mysql
      - backend
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - greenflag_network

  bullboard:
    image: node:20
    container_name: bullboard_container
    restart: always
    working_dir: /app
    volumes:
      - ./BACKEND:/app
    env_file:
      - ./BACKEND/.env
    ports:
      - "3000:3000"
    command: ["node", "src/services/bullboard.js"]
    depends_on:
      - redis
    networks:
      - greenflag_network

volumes:
  mysql_data:

networks:
  greenflag_network:
    driver: bridge
