"use strict";
const { nanoid } = require("nanoid");
module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("events", [
        {
            public_id: nanoid(),
            owner_id: 1,
            title: "Event 1",
            description: "Description for Event 1",
            location: "Location for Event 1",
            capacity: 100,
            start_time: new Date(),
            end_time: new Date(),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            public_id: nanoid(),
            owner_id: 3,
            title: "Event 2",
            description: "Description for Event 2",
            location: "Location for Event 2",
            capacity: 100,
            start_time: new Date(),
            end_time: new Date(),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            public_id: nanoid(),
            owner_id: 4,
            title: "Event 3",
            description: "Description for Event 3",
            location: "Location for Event 3",
            capacity: 100,
            start_time: new Date(),
            end_time: new Date(),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            public_id: nanoid(),
            owner_id: 4,
            title: "Event 4",
            description: "Description for Event 4",
            location: "Location for Event 4",
            capacity: 100,
            start_time: new Date(),
            end_time: new Date(),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            public_id: nanoid(),
            owner_id: 3,
            title: "Event 5",
            description: "Description for Event 5",
            location: "Location for Event 5",
            capacity: 100,
            start_time: new Date(),
            end_time: new Date(),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            public_id: nanoid(),
            owner_id: 1,
            title: "Event 6",
            description: "Description for Event 6",
            location: "Location for Event 6",
            capacity: 100,
            start_time: new Date(),
            end_time: new Date(),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            public_id: nanoid(),
            owner_id: 3,
            title: "Event 7",
            description: "Description for Event 7",
            location: "Location for Event 7",
            capacity: 100,
            start_time: new Date(),
            end_time: new Date(),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            public_id: nanoid(),
            owner_id: 4,
            title: "Event 8",
            description: "Description for Event 8",
            location: "Location for Event 8",
            capacity: 100,
            start_time: new Date(),
            end_time: new Date(),
            created_at: new Date(),
            updated_at: new Date(),
        },
    ]);
    },

    down: async (queryInterface, Sequelize) => {
        return queryInterface.bulkDelete("events", null, {});
    },
};